#!/bin/bash
# Delete all temporary markdown files from root directory
# Keep only: MIGRATION_COMPLETE.md and QUICK_REFERENCE.md

cd C:/development/fincal_projects/portfoliomanager

# List of files to delete (in root directory only)
rm -f USERCONTROLLER_TESTS_FIXED.md
rm -f USERCONTROLLER_MULTIFILE_UPLOAD_TEST_FIXES.md
rm -f SWAGGER_IMPLEMENTATION_COMPLETE.md
rm -f STARTUP_CHECKLIST_FINAL.md
rm -f SPRING_BOOT_FIXES.md
rm -f SCHEMA_VALIDATION_FIX_REPORT.md
rm -f REFACTORING_STATUS.md
rm -f README_FIX_REPORT.md
rm -f README_ANGULAR_21_UPGRADE.md
rm -f QUICK_START_AFTER_FIX.md
rm -f PRE_STARTUP_CHECKLIST.md
rm -f PATH_TO_100_COVERAGE.md
rm -f PACKAGE_REFACTORING_COMPLETE.md
rm -f OPENAPI_DUPLICATE_BEAN_FIXED.md
rm -f OPENAPI_CLEANUP_COMPLETE.md
rm -f MYSQL_KEY_LENGTH_FIX.md
rm -f MISSING_BEANS_FIXED.md
rm -f LANDING_PAGE_IMPLEMENTATION.md
rm -f JACOCO_EXCEPTION_HANDLER_FINAL_REPORT.md
rm -f JACOCO_AND_EXCEPTION_HANDLER_SETUP.md
rm -f IMPLEMENTATION_COMPLETE.md
rm -f IMMEDIATE_ACTION_PLAN.md
rm -f HIBERNATE_MAPPING_FIX_REPORT.md
rm -f FLYWAY_VALIDATION_ERROR_FIX.md
rm -f FLYWAY_MIGRATION_FIX.md
rm -f FIXES_AND_TEST_SUMMARY.md
rm -f FINAL_STATUS_REPORT.md
rm -f FINAL_CONFIRMATION.md
rm -f FEATURE_COMPLETE_SUMMARY.md
rm -f DUPLICATE_BEAN_FIXED.md
rm -f DOCUMENTATION_INDEX.md
rm -f DELIVERABLES_SUMMARY.md
rm -f DELETE_OPENAPICONFIGJAVA.md
rm -f CHECKLIST_COMPLETE.md
rm -f ANGULAR_UPGRADE_21_GUIDE.md
rm -f ANGULAR_21_VISUAL_SUMMARY.md
rm -f ANGULAR_21_UPGRADE_SUMMARY.md
rm -f ANGULAR_21_TECHNICAL_REFERENCE.md
rm -f ANGULAR_21_QUICK_REFERENCE.md
rm -f ANGULAR_21_MASTER_GUIDE.md
rm -f ANGULAR_21_INSTALLATION_SUCCESS.md
rm -f ANGULAR_21_IMPLEMENTATION_CHECKLIST.md
rm -f ANGULAR_21_FINAL_STATUS.md
rm -f ANGULAR_21_BUILD_SUCCESSFUL.md
rm -f ANGULAR_17_VS_21_COMPARISON.md
rm -f AMFI_TEST_COVERAGE_COMPLETE.md
rm -f COMPLETION_CHECKLIST.md
rm -f FINAL_2_STEPS.txt
rm -f FINAL_3_STEPS.txt
rm -f FINAL_ACTION_STEPS.txt
rm -f FINAL_SPRING_BOOT_STATUS.txt
rm -f FLYWAY_FIX.txt
rm -f FLYWAY_FIX_SUMMARY.txt
rm -f FLYWAY_RESET.sql
rm -f FLYWAY_RESET_COMPLETE.sql
rm -f MYSQL_KEY_LENGTH_FIX_SUMMARY.txt
rm -f OPENAPI_CONSOLIDATED.txt
rm -f OPENAPI_FIX_COMPLETE.txt
rm -f QUICK_FIX_GUIDE.txt
rm -f SPRING_BEANS_FIXED_FINAL.txt
rm -f DELETE_TEMP_FILES.bat

# Keep these files:
# MIGRATION_COMPLETE.md - Main comprehensive documentation
# QUICK_REFERENCE.md - Quick lookup reference

echo ""
echo "All temporary markdown and temporary files deleted!"
echo ""
echo "Files kept:"
echo "- MIGRATION_COMPLETE.md"
echo "- QUICK_REFERENCE.md"
echo ""

